name: serverpod_cos
description: Serverpod helpers for Tencent Cloud COS.
version: 0.1.5
repository: https://github.com/Metaildust/serverpod_cos

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  serverpod: ">=3.0.0 <4.0.0"
  tencent_cos_dart: ^0.1.0
